version: 2
updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "query-string"
      - dependency-name: "arrify" # esm-only
      - dependency-name: "p-timeout" # esm-only
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
